server:
  port: 8080

spring:
  application:
    name: aviation-api-wrapper
  main:
    web-application-type: reactive
  cache:
    type: caffeine
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
      roles: ACTUATOR
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

aviation:
  api:
    base-url: https://api.aviationapi.com

http:
  client:
    connect-timeout-ms: 3000
    read-timeout-ms: 5000

cache:
  airports:
    max-size: 1000
    ttl: PT10M

resilience4j:
  retry:
    instances:
      airport-api:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
  circuitbreaker:
    instances:
      airport-api:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      airport-api:
        timeout-duration: 3s
  bulkhead:
    instances:
      airport-api:
        max-concurrent-calls: 50
        max-wait-duration: 0
